export const sampleData = {
  ADMIN: {
    'Academic Supervisors': [
      {
        fullName: 'Dr. Sarah Johnson',
        company: 'Tech Innovations Inc',
        institute: 'Stanford University',
        email: 's.johnson@stanford.edu',
        phone: '650-555-0123',
        account: 'Active',
      },
      {
        fullName: 'Prof. Michael Chen',
        company: 'Data Science Corp',
        institute: 'MIT',
        email: 'm.chen@mit.edu',
        phone: '617-555-0456',
        account: 'Pending',
      },
    ],
    'Industry Clients': [
      {
        fullName: 'Alex Rodriguez',
        company: 'Google',
        institute: 'Industry Partner',
        email: 'a.rodriguez@google.com',
        phone: '415-555-0789',
        account: 'Active',
      },
      {
        fullName: 'Priya Patel',
        company: 'Microsoft',
        institute: 'Tech Alliance',
        email: 'p.patel@microsoft.com',
        phone: '425-555-0345',
        account: 'Active',
      },
    ],
    Projects: [
      {
        project: 'AI Research Platform',
        company: 'Google',
        institute: 'Stanford',
        members: '4',
        deadline: '2023-12-15',
        completion: '75%',
      },
      {
        project: 'Quantum Computing',
        company: 'IBM',
        institute: 'MIT',
        members: '3',
        deadline: '2023-11-30',
        completion: '50%',
      },
    ],
    Tickets: [
      {
        ticketOwner: 'Dr. Johnson',
        issuedBy: 'System',
        title: 'Data Access Issue',
        issuedDate: '2023-10-01',
        dueDate: '2023-10-08',
        type: 'Technical',
      },
      {
        ticketOwner: 'Prof. Chen',
        issuedBy: 'Admin',
        title: 'Account Approval',
        issuedDate: '2023-10-02',
        dueDate: '2023-10-05',
        type: 'Administrative',
      },
    ],
  },
  SUPERVISOR: {
    'Track Progress': [
      {
        project: 'AI Research Platform',
        company: 'Google',
        institute: 'Stanford',
        members: 'Sarah, Priya, Alex',
        deadline: '2023-12-15',
        completion: 'In Progress',
      },
      {
        project: 'Quantum Computing',
        company: 'IBM',
        institute: 'MIT',
        members: 'Michael, David',
        deadline: '2023-11-30',
        completion: 'Behind Schedule',
      },
    ],
    'Monitor Students': [
      {
        student: 'Emily Wilson',
        institute: 'Stanford',
        project: 'AI Research Platform',
        performance: 'Excellent',
        industry: 'Google',
        action: 'Review Needed',
      },
      {
        student: 'James Lee',
        institute: 'MIT',
        project: 'Quantum Computing',
        performance: 'Good',
        industry: 'IBM',
        action: 'On Track',
      },
    ],
  },
  CLIENT: {
    Dashboard: [
      {
        project: 'E-commerce Platform',
        status: 'In Progress',
        projectManager: 'Dr. Johnson',
        startDate: '2023-09-01',
        endDate: '2023-12-15',
        viewDetails: 'View',
      },
      {
        project: 'Data Analytics Dashboard',
        status: 'Completed',
        projectManager: 'Prof. Chen',
        startDate: '2023-07-15',
        endDate: '2023-09-30',
        viewDetails: 'View',
      },
    ],
    'Track Progress': [
      {
        project: 'E-commerce Platform',
        projectManager: 'Dr. Johnson',
        startDate: '2023-09-01',
        endDate: '2023-12-15',
        status: 'In Progress',
        progress: '65%',
      },
      {
        project: 'Data Analytics Dashboard',
        projectManager: 'Prof. Chen',
        startDate: '2023-07-15',
        endDate: '2023-09-30',
        status: 'Completed',
        progress: '100%',
      },
    ],
    'Pending Approvals': [
      {
        project: 'E-commerce Platform',
        team: 'Web Dev Team',
        projectManager: 'Dr. Johnson',
        viewDetails: 'Review',
        pendingApproval: 'Design Mockups',
      },
      {
        project: 'Mobile App',
        team: 'Mobile Team',
        projectManager: 'Prof. Chen',
        viewDetails: 'Review',
        pendingApproval: 'API Integration',
      },
    ],
  },
  STUDENT: {
    Projects: [
      {
        project: 'AI Research Assistant',
        projectClient: 'Stanford Hospital',
        projectCategory: 'Healthcare AI',
        dueDate: '2023-11-15',
        status: 'In Progress',
      },
      {
        project: 'Campus Navigation App',
        projectClient: 'University',
        projectCategory: 'Mobile Development',
        dueDate: '2023-12-01',
        status: 'Planning',
      },
    ],
    'Track Project': [
      {
        project: 'AI Research Assistant',
        company: 'Stanford Hospital',
        institute: 'Stanford',
        members: 'Emily, James',
        deadline: '2023-11-15',
        status: 'Active',
      },
      {
        project: 'Campus Navigation App',
        company: 'Stanford University',
        institute: 'Computer Science Dept',
        members: 'Emily, Sarah',
        deadline: '2023-12-01',
        status: 'Planning',
      },
    ],
  },
};
