import {
  House,
  ChartBar,
  Users,
  FileText,
  Mail,
  User,
  Clock,
  Bookmark,
} from 'lucide-react';

export const userDashboardConfig = {
  ADMIN: {
    navItems: [
      {
        id: 1,
        label: 'Dashboard',
        icon: House,
        hasTable: false,
        component: <AdminDashboard />,
      },
      {
        id: 2,
        label: 'Academic Supervisors',
        icon: User,
        columns: [
          { key: 'fullName', title: 'Full Name' },
          { key: 'company', title: 'Company' },
          { key: 'institute', title: 'Institute' },
          { key: 'email', title: 'Email' },
          { key: 'phone', title: 'Phone Number' },
          { key: 'account', title: 'Account' },
        ],
      },
      {
        id: 3,
        label: 'Industry Clients',
        icon: Users,
        columns: [
          { key: 'fullName', title: 'Full Name' },
          { key: 'company', title: 'Company' },
          { key: 'institute', title: 'Institute' },
          { key: 'email', title: 'Email' },
          { key: 'phone', title: 'Phone Number' },
          { key: 'account', title: 'Account' },
        ],
      },
      {
        id: 4,
        label: 'Projects',
        icon: FileText,
        columns: [
          { key: 'project', title: 'Project' },
          { key: 'company', title: 'Company' },
          { key: 'institute', title: 'Institute' },
          { key: 'members', title: 'Members' },
          { key: 'deadline', title: 'Deadline' },
          { key: 'completion', title: 'Completion' },
        ],
      },
      {
        id: 5,
        label: 'Tickets',
        icon: Bookmark,
        columns: [
          { key: 'ticketOwner', title: 'Ticket Owner' },
          { key: 'issuedBy', title: 'Issued By' },
          { key: 'title', title: 'Title' },
          { key: 'issuedDate', title: 'Issued Date' },
          { key: 'dueDate', title: 'Due Date' },
          { key: 'type', title: 'Type' },
        ],
      },
    ],
    showNewProjectButton: false,
  },
  SUPERVISOR: {
    navItems: [
      {
        id: 1,
        label: 'Track Progress',
        icon: ChartBar,
        columns: [
          { key: 'project', title: 'Project' },
          { key: 'company', title: 'Company' },
          { key: 'institute', title: 'Institute' },
          { key: 'members', title: 'Members' },
          { key: 'deadline', title: 'Deadline' },
          { key: 'completion', title: 'Completion' },
        ],
      },
      {
        id: 2,
        label: 'Monitor Students',
        icon: Users,
        columns: [
          { key: 'student', title: 'Student' },
          { key: 'institute', title: 'Institute' },
          { key: 'project', title: 'Project' },
          { key: 'performance', title: 'Performance' },
          { key: 'industry', title: 'Industry' },
          { key: 'action', title: 'Action' },
        ],
      },
    ],
    showNewProjectButton: false,
  },
  CLIENT: {
    navItems: [
      {
        id: 1,
        label: 'Dashboard',
        icon: House,
        columns: [
          { key: 'project', title: 'Project' },
          { key: 'status', title: 'Project Status' },
          { key: 'projectManager', title: 'Project Manager' },
          { key: 'startDate', title: 'Start Date' },
          { key: 'endDate', title: 'End Date' },
          { key: 'viewDetails', title: 'View Details' },
        ],
      },
      {
        id: 2,
        label: 'Track Progress',
        icon: ChartBar,
        columns: [
          { key: 'project', title: 'Project' },
          { key: 'projectManager', title: 'Project Manager' },
          { key: 'startDate', title: 'Start Date' },
          { key: 'endDate', title: 'End Date' },
          { key: 'status', title: 'Project Status' },
          { key: 'progress', title: 'Progress' },
        ],
      },
      {
        id: 3,
        label: 'Pending Approvals',
        icon: Clock,
        columns: [
          { key: 'project', title: 'Project' },
          { key: 'team', title: 'Team' },
          { key: 'projectManager', title: 'Project Manager' },
          { key: 'viewDetails', title: 'View Details' },
          { key: 'pendingApproval', title: 'Pending Approval' },
        ],
      },
    ],
    showNewProjectButton: true,
  },
  STUDENT: {
    navItems: [
      {
        id: 1,
        label: 'Dashboard',
        icon: House,
        hasTable: false,
        component: <StudentDashboard />,
      },
      {
        id: 2,
        label: 'Projects',
        icon: FileText,
        columns: [
          { key: 'project', title: 'Project' },
          { key: 'projectClient', title: 'Project Client' },
          { key: 'projectCategory', title: 'Project Category' },
          { key: 'dueDate', title: 'Due Date' },
          { key: 'status', title: 'Project Status' },
        ],
      },
      {
        id: 3,
        label: 'Mail',
        icon: Mail,
        hasTable: false,
        component: <StudentMail />,
      },
      {
        id: 4,
        label: 'Track Project',
        icon: ChartBar,
        columns: [
          { key: 'project', title: 'Project' },
          { key: 'company', title: 'Company' },
          { key: 'institute', title: 'Institute' },
          { key: 'members', title: 'Members' },
          { key: 'deadline', title: 'Deadline' },
          { key: 'status', title: 'Status' },
        ],
      },
    ],
    showNewProjectButton: false,
  },
};
